# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHhv801ISvnDEN48jnwU_rlWz7xTXOmv
"""

# IMPORT LIBRARY
from IPython.display import display

import pandas as pd
import warnings

warnings.filterwarnings("ignore")

# PENGATURAN TAMPILAN DATAFRAME

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

# 1. LOAD DATASET

print("="*90)
print("1. LOAD DATASET")
print("="*90)

DATA_PATH = r"C:\honeypot-risk-classifier\datasets\hp_upnvj_1.honeypots2_500000data.csv"

df = pd.read_csv(
    DATA_PATH,
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

# Simpan dataset asli
df_raw = df.copy()

# RINGKASAN DATASET

print("\nRINGKASAN DATASET")

summary = pd.DataFrame({
    "Informasi": [
        "Nama File",
        "Jumlah Baris",
        "Jumlah Kolom"
    ],
    "Nilai": [
        DATA_PATH,
        len(df),
        len(df.columns)
    ]
})

display(summary)

# STRUKTUR ATRIBUT DATASET

print("\nSTRUKTUR ATRIBUT DATASET")

struktur = pd.DataFrame({
    "No": range(1, len(df.columns)+1),
    "Nama Kolom": df.columns,
    "Tipe Data": df.dtypes.values
})

display(struktur)

# ANALISIS MISSING VALUE

print("\nANALISIS MISSING VALUE")

missing = pd.DataFrame({
    "No": range(1, len(df.columns)+1),
    "Nama Kolom": df.columns,
    "Missing Value": df.isnull().sum().values,
    "Persentase (%)": (
        df.isnull().sum()/len(df)*100
    ).round(2)
})

display(missing)

print("\nKOLOM YANG MEMILIKI MISSING VALUE")

display(
    missing[
        missing["Missing Value"] > 0
    ]
)

# ANALISIS DATA DUPLIKAT

print("\nANALISIS DATA DUPLIKAT")

duplicate_df = pd.DataFrame({
    "Keterangan": [
        "Jumlah Data",
        "Jumlah Data Duplikat"
    ],
    "Nilai": [
        len(df),
        df.duplicated().sum()
    ]
})

display(duplicate_df)

# JUMLAH NILAI UNIK

print("\nJUMLAH NILAI UNIK SETIAP KOLOM")

unique_df = pd.DataFrame({
    "No": range(1, len(df.columns)+1),
    "Nama Kolom": df.columns,
    "Jumlah Nilai Unik": [
        df[col].nunique(dropna=True)
        for col in df.columns
    ]
})

display(unique_df)

# CONTOH DATASET ASLI

print("\n" + "="*90)
print("50 BARIS PERTAMA DATASET ASLI")
print("="*90)

# Kolom yang ditampilkan

# 25 kolom pertama
kolom_awal = list(df.columns[:25])

# Kolom terakhir (misalnya kolom ke-148)
kolom_akhir = [df.columns[-1]]

# Gabungkan
kolom_tampil = kolom_awal + kolom_akhir

# Ambil 50 baris pertama
dataset_awal = df.loc[:49, kolom_tampil].copy()

# Rename kolom terakhir supaya terlihat bahwa ada kolom yang disembunyikan
dataset_awal.rename(
    columns={
        df.columns[-1]:
        f"... {df.columns[-1]}"
    },
    inplace=True
)

display(dataset_awal)

print("\nKeterangan:")
print(f"- Total Kolom Dataset        : {len(df.columns)}")
print(f"- Kolom Ditampilkan          : 25 kolom pertama + kolom terakhir")
print(f"- Kolom Disembunyikan        : {len(df.columns)-26} kolom")
print(f"- Jumlah Baris Ditampilkan   : {len(dataset_awal)}")

# 2. PREPROCESSING DATA

print("\n" + "="*90)
print("2. PREPROCESSING DATA")
print("="*90)

# DATASET SEBELUM PREPROCESSING

print("\nDATASET SEBELUM PREPROCESSING")

display(df.head(50))

print("\nJumlah Data Sebelum :", len(df))
print("Jumlah Kolom Sebelum :", len(df.columns))

# Simpan untuk perbandingan
df_before = df.copy()

# MEMBERSIHKAN NAMA KOLOM

df.columns = (
    df.columns
      .str.lower()
      .str.strip()
)

# MENGHAPUS KOLOM UNNAMED

print("\nMenghapus Kolom Unnamed")

jumlah_kolom_awal = len(df.columns)

df = df.loc[:, ~df.columns.str.contains("^unnamed")]

jumlah_kolom_setelah = len(df.columns)

print("Jumlah Kolom Awal :", jumlah_kolom_awal)
print("Jumlah Kolom Setelah :", jumlah_kolom_setelah)

# ATRIBUT PENELITIAN

use_cols = [
    "fields.source_address",
    "fields.login",
    "fields.target_port",
    "fields.username",
    "fields.password",
    "fields.sessionid"
]

print("\nAtribut Penelitian")

display(pd.DataFrame({
    "No": range(1,len(use_cols)+1),
    "Atribut": use_cols
}))

# SELEKSI ATRIBUT

df = df[use_cols]

print("\nDataset Setelah Seleksi Atribut")

display(df.head(50))

# MISSING VALUE

print("\nAnalisis Missing Value Sebelum Cleaning")

missing_before = pd.DataFrame({
    "Atribut": df.columns,
    "Missing Value": df.isnull().sum().values
})

display(missing_before)

# DATA CLEANING

jumlah_sebelum = len(df)

df = df.dropna()

jumlah_setelah = len(df)

print("\nJumlah Data Sebelum Cleaning :", jumlah_sebelum)
print("Jumlah Data Setelah Cleaning :", jumlah_setelah)

# KONVERSI TIPE DATA

df["fields.target_port"] = pd.to_numeric(
    df["fields.target_port"],
    errors="coerce"
)

df = df.dropna()

# STANDARDISASI LOGIN

df["fields.login"] = (
    df["fields.login"]
      .astype(str)
      .str.lower()
      .str.strip()
)

# MISSING VALUE SESUDAH CLEANING

print("\nMissing Value Setelah Cleaning")

missing_after = pd.DataFrame({
    "Atribut": df.columns,
    "Missing Value": df.isnull().sum().values
})

display(missing_after)

# RINGKASAN PREPROCESSING

summary_preprocessing = pd.DataFrame({

    "Keterangan":[

        "Jumlah Record Sebelum",

        "Jumlah Record Sesudah",

        "Jumlah Kolom Sebelum",

        "Jumlah Kolom Sesudah"

    ],

    "Nilai":[

        jumlah_sebelum,

        jumlah_setelah,

        jumlah_kolom_awal,

        len(df.columns)

    ]

})

print("\nRingkasan Preprocessing")

display(summary_preprocessing)

# DATASET SETELAH PREPROCESSING

print("\nDataset Setelah Preprocessing")

display(df.head(50))

# 3. FEATURE ENGINEERING

print("\n" + "="*90)
print("3. FEATURE ENGINEERING")
print("="*90)

# DATASET SEBELUM FEATURE ENGINEERING

print("\nDATASET SEBELUM FEATURE ENGINEERING")

display(df.head(50))

print("\nRINGKASAN DATASET SEBELUM FEATURE ENGINEERING")

ringkasan_awal = pd.DataFrame({
    "Keterangan":[
        "Jumlah Record",
        "Jumlah Kolom"
    ],
    "Nilai":[
        len(df),
        len(df.columns)
    ]
})

display(ringkasan_awal)

# Simpan dataset sebelum FE
df_before_fe = df.copy()

# HUBUNGAN ATRIBUT DENGAN FITUR

print("\nPEMETAAN ATRIBUT PENELITIAN MENJADI FITUR")

mapping = pd.DataFrame({

    "Atribut Penelitian":[

        "fields.source_address",

        "fields.login",

        "fields.login",

        "fields.login",

        "fields.login",

        "fields.login",

        "fields.target_port",

        "fields.username",

        "fields.password",

        "fields.sessionid"

    ],

    "Fitur Yang Dibentuk":[

        "Grouping Source IP",

        "connection_count",

        "failed",

        "success",

        "failed_ratio",

        "success_ratio",

        "unique_ports",

        "unique_username",

        "unique_password",

        "session_count"

    ],

    "Metode":[

        "groupby()",

        "count()",

        "sum()",

        "sum()",

        "failed / connection_count",

        "success / connection_count",

        "nunique()",

        "nunique()",

        "nunique()",

        "nunique()"

    ]

})

display(mapping)

# PROSES FEATURE ENGINEERING

features = df.groupby("fields.source_address").agg(

    connection_count=("fields.login","count"),

    failed=("fields.login",
            lambda x:(x=="fail").sum()),

    success=("fields.login",
             lambda x:(x=="success").sum()),

    unique_ports=("fields.target_port","nunique"),

    unique_username=("fields.username","nunique"),

    unique_password=("fields.password","nunique"),

    session_count=("fields.sessionid","nunique")

).reset_index()

# MEMBENTUK FITUR RASIO

features["failed_ratio"] = (
    features["failed"] /
    features["connection_count"]
)

features["success_ratio"] = (
    features["success"] /
    features["connection_count"]
)

features.fillna(0, inplace=True)

# PERBANDINGAN SEBELUM DAN SESUDAH

jumlah_record_awal = len(df_before_fe)
jumlah_record_akhir = len(features)

jumlah_kolom_awal = len(df_before_fe.columns)
jumlah_kolom_akhir = len(features.columns)

persentase_pengurangan = round(
    (
        (jumlah_record_awal - jumlah_record_akhir)
        / jumlah_record_awal
    ) * 100,
    2
)

print("\nPERBANDINGAN SEBELUM DAN SESUDAH FEATURE ENGINEERING")

ringkasan_fe = pd.DataFrame({

    "Keterangan":[

        "Jumlah Record Sebelum",

        "Jumlah Record Sesudah",

        "Jumlah Record Berkurang",

        "Persentase Pengurangan (%)",

        "Jumlah Kolom Sebelum",

        "Jumlah Kolom Sesudah"

    ],

    "Nilai":[

        jumlah_record_awal,

        jumlah_record_akhir,

        jumlah_record_awal-jumlah_record_akhir,

        persentase_pengurangan,

        jumlah_kolom_awal,

        jumlah_kolom_akhir

    ]

})

display(ringkasan_fe)

# DAFTAR FITUR HASIL FEATURE ENGINEERING

print("\nDAFTAR FITUR YANG DIHASILKAN")

fitur = pd.DataFrame({

    "No":range(1,10),

    "Nama Fitur":[

        "connection_count",

        "failed",

        "success",

        "unique_ports",

        "unique_username",

        "unique_password",

        "session_count",

        "failed_ratio",

        "success_ratio"

    ],

    "Keterangan":[

        "Jumlah seluruh koneksi",

        "Jumlah login gagal",

        "Jumlah login berhasil",

        "Jumlah port unik",

        "Jumlah username unik",

        "Jumlah password unik",

        "Jumlah session unik",

        "Rasio login gagal",

        "Rasio login berhasil"

    ]

})

display(fitur)

# DATASET HASIL FEATURE ENGINEERING

print("\nDATASET HASIL FEATURE ENGINEERING")

display(features.head(50))

# STATISTIK DESKRIPTIF

print("\nSTATISTIK DESKRIPTIF FITUR")

display(features.describe())

# 4. BUILD PSEUDO LABEL

print("\n" + "="*90)
print("4. BUILD PSEUDO LABEL")
print("="*90)

# DATASET SEBELUM PSEUDO LABELING

print("\nDATASET SEBELUM PSEUDO LABELING")

display(features.head(50))

print("\nJumlah Source IP :", len(features))
print("Jumlah Kolom     :", len(features.columns))

# Simpan dataset sebelum pseudo labeling
features_before_label = features.copy()

# MENENTUKAN THRESHOLD Q90
q90_failed = features["failed"].quantile(0.90)
q90_conn = features["connection_count"].quantile(0.90)
q90_ratio = features["failed_ratio"].quantile(0.90)
q90_user = features["unique_username"].quantile(0.90)
q90_pass = features["unique_password"].quantile(0.90)

print("\nTHRESHOLD QUANTILE 90%")

threshold_df = pd.DataFrame({

    "Indikator":[
        "Failed Login",
        "Connection Count",
        "Failed Ratio",
        "Unique Username",
        "Unique Password"
    ],

    "Threshold Q90":[
        q90_failed,
        q90_conn,
        q90_ratio,
        q90_user,
        q90_pass
    ]

})

display(threshold_df)

# EVALUASI MASING-MASING INDIKATOR
features["failed_q90"] = (
    features["failed"] >= q90_failed
).astype(int)

features["connection_q90"] = (
    features["connection_count"] >= q90_conn
).astype(int)

features["failed_ratio_q90"] = (
    features["failed_ratio"] >= q90_ratio
).astype(int)

features["username_q90"] = (
    features["unique_username"] >= q90_user
).astype(int)

features["password_q90"] = (
    features["unique_password"] >= q90_pass
).astype(int)

# PERHITUNGAN RISK SCORE
features["risk_score"] = (

    features["failed_q90"]

    +

    features["connection_q90"]

    +

    features["failed_ratio_q90"]

    +

    features["username_q90"]

    +

    features["password_q90"]

)

print("\nPROSES PERHITUNGAN RISK SCORE")

display(

    features[[
        "fields.source_address",

        "failed",
        "failed_q90",

        "connection_count",
        "connection_q90",

        "failed_ratio",
        "failed_ratio_q90",

        "unique_username",
        "username_q90",

        "unique_password",
        "password_q90",

        "risk_score"
    ]].head(50)

)

# PEMBENTUKAN LABEL
features["risk_label"] = (

    features["risk_score"] >= 2

).astype(int)

features["kategori"] = features["risk_label"].map({

    0:"Low Risk",

    1:"High Risk"

})

# DATASET SETELAH PSEUDO LABELING
print("\nDATASET SETELAH PSEUDO LABELING")

display(features.head(50))

# DISTRIBUSI LABEL
label = features["kategori"].value_counts()

persen = round(label/len(features)*100,2)

label_df = pd.DataFrame({

    "Kategori":[
        "Low Risk",
        "High Risk"
    ],

    "Jumlah":[
        label.get("Low Risk",0),
        label.get("High Risk",0)
    ],

    "Persentase (%)":[
        persen.get("Low Risk",0),
        persen.get("High Risk",0)
    ]

})

print("\nDISTRIBUSI LABEL")

display(label_df)

# RINGKASAN PSEUDO LABELING
summary = pd.DataFrame({

    "Keterangan":[
        "Jumlah Source IP",
        "Low Risk",
        "High Risk"
    ],

    "Nilai":[
        len(features),
        label.get("Low Risk",0),
        label.get("High Risk",0)
    ]

})

print("\nRINGKASAN PSEUDO LABELING")

display(summary)

# VISUALISASI
import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))

plt.pie(

    label,

    labels=label.index,

    autopct="%1.1f%%",

    startangle=90

)

plt.title("Distribusi Pseudo Label")

plt.show()

# 5. PREPARE TRAINING DATA
print("\n" + "="*90)
print("5. PREPARE TRAINING DATA")
print("="*90)

# FITUR YANG DIGUNAKAN
feature_columns = [

    "success",

    "success_ratio",

    "unique_ports",

    "unique_username",

    "unique_password",

    "session_count"

]

target_column = "risk_label"

print("\nFITUR INPUT")

display(pd.DataFrame({

    "No": range(1, len(feature_columns)+1),

    "Nama Fitur": feature_columns

}))

print("\nTARGET KLASIFIKASI")

display(pd.DataFrame({

    "Target": [target_column],

    "Keterangan": ["Label Risiko (Low Risk / High Risk)"]

}))

# MEMBENTUK DATA TRAINING
X = features[feature_columns]

y = features[target_column]

# RINGKASAN DATA TRAINING
summary_training = pd.DataFrame({

    "Keterangan":[

        "Jumlah Record",

        "Jumlah Fitur",

        "Jumlah Target"

    ],

    "Nilai":[

        len(X),

        X.shape[1],

        1

    ]

})

print("\nRINGKASAN DATA TRAINING")

display(summary_training)

# DATA FITUR (X)
print("\nDATA FITUR (X)")

display(X.head(50))

print("\nShape X :", X.shape)

# DATA TARGET (y)
print("\nDATA TARGET (y)")

display(y.head(50).to_frame())

print("\nShape y :", y.shape)

# DISTRIBUSI TARGET
print("\nDISTRIBUSI TARGET")

target_distribution = pd.DataFrame({

    "Label":[

        "Low Risk",

        "High Risk"

    ],

    "Jumlah":[

        (y == 0).sum(),

        (y == 1).sum()

    ],

    "Persentase (%)":[

        round((y == 0).sum()/len(y)*100,2),

        round((y == 1).sum()/len(y)*100,2)

    ]

})

display(target_distribution)

# 6. TRAIN TEST SPLIT
print("\n" + "="*90)
print("6. TRAIN TEST SPLIT")
print("="*90)

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# PEMBAGIAN DATA
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,
    stratify=y,
    random_state=42

)

# RINGKASAN TRAIN TEST SPLIT
summary_split = pd.DataFrame({

    "Dataset":[

        "Total Dataset",
        "Training Dataset",
        "Testing Dataset"

    ],

    "Jumlah Data":[

        len(X),
        len(X_train),
        len(X_test)

    ],

    "Persentase":[

        "100%",
        "80%",
        "20%"

    ]

})

print("\nRINGKASAN PEMBAGIAN DATA")

display(summary_split)

# SHAPE DATA
shape_df = pd.DataFrame({

    "Dataset":[

        "X",
        "X_train",
        "X_test",
        "y",
        "y_train",
        "y_test"

    ],

    "Shape":[

        str(X.shape),
        str(X_train.shape),
        str(X_test.shape),
        str(y.shape),
        str(y_train.shape),
        str(y_test.shape)

    ]

})

print("\nDIMENSI DATASET")

display(shape_df)

# DISTRIBUSI LABEL TRAINING
train_distribution = pd.DataFrame({

    "Label":[

        "Low Risk",
        "High Risk"

    ],

    "Jumlah":[

        (y_train==0).sum(),
        (y_train==1).sum()

    ]

})

train_distribution["Persentase (%)"] = (

    train_distribution["Jumlah"] /

    len(y_train) *100

).round(2)

print("\nDISTRIBUSI LABEL DATA TRAINING")

display(train_distribution)

# DISTRIBUSI LABEL TESTING
test_distribution = pd.DataFrame({

    "Label":[

        "Low Risk",
        "High Risk"

    ],

    "Jumlah":[

        (y_test==0).sum(),
        (y_test==1).sum()

    ]

})

test_distribution["Persentase (%)"]=(

    test_distribution["Jumlah"]/

    len(y_test)*100

).round(2)

print("\nDISTRIBUSI LABEL DATA TESTING")

display(test_distribution)

# DATA TRAINING
print("\n50 DATA TRAINING (X_train)")

display(X_train.head(50))

print("\n50 LABEL TRAINING (y_train)")

display(y_train.head(50).to_frame())

# DATA TESTING
print("\n50 DATA TESTING (X_test)")

display(X_test.head(50))

print("\n50 LABEL TESTING (y_test)")

display(y_test.head(50).to_frame())

# VISUALISASI PEMBAGIAN DATA
plt.figure(figsize=(6,4))

plt.bar(

    ["Training","Testing"],

    [

        len(X_train),

        len(X_test)

    ]

)

plt.title("Perbandingan Jumlah Data Training dan Testing")

plt.ylabel("Jumlah Data")

plt.show()

# VISUALISASI DISTRIBUSI LABEL
label_compare = pd.DataFrame({

    "Training":[

        (y_train==0).sum(),
        (y_train==1).sum()

    ],

    "Testing":[

        (y_test==0).sum(),
        (y_test==1).sum()

    ]

},

index=[

    "Low Risk",
    "High Risk"

])

label_compare.plot(

    kind="bar",

    figsize=(7,5)

)

plt.title("Distribusi Label Training dan Testing")

plt.ylabel("Jumlah Data")

plt.xticks(rotation=0)

plt.show()

# KETERANGAN
print("\nKETERANGAN")

print(f"Total Dataset     : {len(X)}")

print(f"Training Dataset  : {len(X_train)} (80%)")

print(f"Testing Dataset   : {len(X_test)} (20%)")

print("\nMetode Split      : Stratified Train-Test Split")

print("Random State      : 42")

# 7. PENYEIMBANGAN DATA MENGGUNAKAN SMOTE
print("\n" + "="*90)
print("7. PENYEIMBANGAN DATA MENGGUNAKAN SMOTE")
print("="*90)

from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt

# DATA SEBELUM SMOTE
print("\n50 DATA TRAINING SEBELUM SMOTE")

display(X_train.head(50))

print("\n50 LABEL TRAINING SEBELUM SMOTE")

display(y_train.head(50).to_frame())

# DISTRIBUSI KELAS SEBELUM SMOTE
before_smote = pd.DataFrame({

    "Label":[

        "Low Risk",

        "High Risk"

    ],

    "Jumlah":[

        (y_train==0).sum(),

        (y_train==1).sum()

    ]

})

before_smote["Persentase (%)"] = (

    before_smote["Jumlah"] /

    len(y_train) *100

).round(2)

print("\nDISTRIBUSI KELAS SEBELUM SMOTE")

display(before_smote)

# SHAPE SEBELUM SMOTE
shape_before = pd.DataFrame({

    "Dataset":[

        "X_train",

        "y_train"

    ],

    "Shape":[

        str(X_train.shape),

        str(y_train.shape)

    ]

})

print("\nDIMENSI DATA SEBELUM SMOTE")

display(shape_before)

# VISUALISASI SEBELUM SMOTE
plt.figure(figsize=(6,4))

plt.bar(

    before_smote["Label"],

    before_smote["Jumlah"]

)

plt.title("Distribusi Kelas Sebelum SMOTE")

plt.ylabel("Jumlah Data")

plt.show()

# PROSES SMOTE
smote = SMOTE(

    random_state=42

)

X_train_smote, y_train_smote = smote.fit_resample(

    X_train,

    y_train

)

# DATA SESUDAH SMOTE
print("\n50 DATA TRAINING SESUDAH SMOTE")

display(X_train_smote.head(50))

print("\n50 LABEL TRAINING SESUDAH SMOTE")

display(y_train_smote.head(50).to_frame())

# DISTRIBUSI KELAS SESUDAH SMOTE
after_smote = pd.DataFrame({

    "Label":[

        "Low Risk",

        "High Risk"

    ],

    "Jumlah":[

        (y_train_smote==0).sum(),

        (y_train_smote==1).sum()

    ]

})

after_smote["Persentase (%)"]=(

    after_smote["Jumlah"]/

    len(y_train_smote)*100

).round(2)

print("\nDISTRIBUSI KELAS SESUDAH SMOTE")

display(after_smote)

# SHAPE SESUDAH SMOTE
shape_after = pd.DataFrame({

    "Dataset":[

        "X_train_smote",

        "y_train_smote"

    ],

    "Shape":[

        str(X_train_smote.shape),

        str(y_train_smote.shape)

    ]

})

print("\nDIMENSI DATA SESUDAH SMOTE")

display(shape_after)

# VISUALISASI SESUDAH SMOTE
plt.figure(figsize=(6,4))

plt.bar(

    after_smote["Label"],

    after_smote["Jumlah"]

)

plt.title("Distribusi Kelas Sesudah SMOTE")

plt.ylabel("Jumlah Data")

plt.show()

# PERBANDINGAN SEBELUM DAN SESUDAH SMOTE
comparison = pd.DataFrame({

    "Label":[

        "Low Risk",

        "High Risk"

    ],

    "Sebelum SMOTE":[

        (y_train==0).sum(),

        (y_train==1).sum()

    ],

    "Sesudah SMOTE":[

        (y_train_smote==0).sum(),

        (y_train_smote==1).sum()

    ]

})

print("\nPERBANDINGAN DISTRIBUSI KELAS")

display(comparison)

# RINGKASAN SMOTE
summary_smote = pd.DataFrame({

    "Keterangan":[

        "Jumlah Data Sebelum SMOTE",

        "Jumlah Data Sesudah SMOTE",

        "Penambahan Data",

        "Metode",

        "Random State"

    ],

    "Nilai":[

        len(y_train),

        len(y_train_smote),

        len(y_train_smote)-len(y_train),

        "SMOTE",

        42

    ]

})

print("\nRINGKASAN PROSES SMOTE")

display(summary_smote)

# 8. PELATIHAN MODEL RANDOM FOREST
print("\n" + "="*90)
print("8. PELATIHAN MODEL RANDOM FOREST")
print("="*90)

from sklearn.ensemble import RandomForestClassifier
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

# PARAMETER RANDOM FOREST
rf = RandomForestClassifier(

    n_estimators=300,
    max_depth=8,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42

)

# MEMBANGUN PIPELINE
pipeline = Pipeline([

    ("smote", SMOTE(random_state=42)),

    ("rf", rf)

])

# TABEL PARAMETER RANDOM FOREST
parameter_df = pd.DataFrame({

    "Parameter":[

        "Algorithm",
        "Number of Trees",
        "Maximum Depth",
        "Minimum Samples Split",
        "Minimum Samples Leaf",
        "Class Weight",
        "Random State"

    ],

    "Value":[

        "Random Forest",
        300,
        8,
        10,
        5,
        "balanced",
        42

    ]

})

print("\nPARAMETER RANDOM FOREST")

display(parameter_df)

# INFORMASI PIPELINE
pipeline_df = pd.DataFrame({

    "Tahapan":[

        "Input Data Training",

        "SMOTE",

        "Random Forest",

        "Output"

    ],

    "Proses":[

        "X_train & y_train",

        "Menyeimbangkan kelas minoritas",

        "Pelatihan model klasifikasi",

        "Model Random Forest"

    ]

})

print("\nALUR PIPELINE PELATIHAN")

display(pipeline_df)

# DATA TRAINING
training_summary = pd.DataFrame({

    "Keterangan":[

        "Jumlah Data Training",

        "Jumlah Feature",

        "Jumlah Target"

    ],

    "Nilai":[

        len(X_train),

        X_train.shape[1],

        len(y_train)

    ]

})

print("\nRINGKASAN DATA TRAINING")

display(training_summary)

print("\n50 DATA TRAINING")

display(X_train.head(50))

print("\n50 LABEL TRAINING")

display(y_train.head(50).to_frame())

# MELATIH MODEL
pipeline.fit(

    X_train,

    y_train

)

print("\nMODEL RANDOM FOREST BERHASIL DILATIH")

# RINGKASAN HASIL PELATIHAN
model_summary = pd.DataFrame({

    "Keterangan":[

        "Algoritma",

        "Jumlah Pohon",

        "Data Training",

        "Jumlah Feature",

        "Status Model"

    ],

    "Nilai":[

        "Random Forest",

        300,

        len(X_train),

        X_train.shape[1],

        "Berhasil Dilatih"

    ]

})

print("\nRINGKASAN HASIL PELATIHAN")

display(model_summary)

# 9. CROSS VALIDATION
print("\n" + "="*90)
print("9. CROSS VALIDATION")
print("="*90)

from sklearn.model_selection import StratifiedKFold, cross_validate

# STRATIFIED K-FOLD
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# PARAMETER CROSS VALIDATION
cv_parameter = pd.DataFrame({
    "Parameter":[
        "Validation Method",
        "Number of Folds",
        "Shuffle",
        "Random State"
    ],
    "Value":[
        "Stratified K-Fold",
        5,
        True,
        42
    ]
})

print("\nPARAMETER CROSS VALIDATION")

display(cv_parameter)

# CROSS VALIDATION
scores = cross_validate(
    pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring=[
        "accuracy",
        "precision",
        "recall",
        "f1",
        "roc_auc"
    ],
    return_train_score=False
)

# HASIL SETIAP FOLD
fold_result = pd.DataFrame({

    "Fold":[1,2,3,4,5],

    "Accuracy":scores["test_accuracy"],

    "Precision":scores["test_precision"],

    "Recall":scores["test_recall"],

    "F1-Score":scores["test_f1"],

    "ROC AUC":scores["test_roc_auc"]

})

print("\nHASIL CROSS VALIDATION SETIAP FOLD")

display(fold_result)

# RATA-RATA HASIL CROSS VALIDATION
mean_result = pd.DataFrame({

    "Metric":[

        "Accuracy",

        "Precision",

        "Recall",

        "F1-Score",

        "ROC AUC"

    ],

    "Mean Score":[

        scores["test_accuracy"].mean(),

        scores["test_precision"].mean(),

        scores["test_recall"].mean(),

        scores["test_f1"].mean(),

        scores["test_roc_auc"].mean()

    ]

})

print("\nRATA-RATA HASIL CROSS VALIDATION")

display(mean_result)

# STANDAR DEVIASI
std_result = pd.DataFrame({

    "Metric":[

        "Accuracy",

        "Precision",

        "Recall",

        "F1-Score",

        "ROC AUC"

    ],

    "Standard Deviation":[

        scores["test_accuracy"].std(),

        scores["test_precision"].std(),

        scores["test_recall"].std(),

        scores["test_f1"].std(),

        scores["test_roc_auc"].std()

    ]

})

print("\nSTANDAR DEVIASI HASIL CROSS VALIDATION")

display(std_result)

# VISUALISASI ACCURACY SETIAP FOLD
plt.figure(figsize=(8,5))

plt.bar(
    fold_result["Fold"],
    fold_result["Accuracy"]
)

plt.title("Accuracy pada Setiap Fold")

plt.xlabel("Fold")

plt.ylabel("Accuracy")

plt.xticks(fold_result["Fold"])

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.show()

# VISUALISASI SELURUH METRIK
metric_mean = mean_result.set_index("Metric")

plt.figure(figsize=(8,5))

plt.bar(
    metric_mean.index,
    metric_mean["Mean Score"]
)

plt.title("Rata-rata Hasil Cross Validation")

plt.ylabel("Score")

plt.ylim(0,1)

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.show()

print("\nCROSS VALIDATION SELESAI")

# 10. EVALUASI MODEL RANDOM FOREST
print("\n" + "="*90)
print("10. EVALUASI MODEL RANDOM FOREST")
print("="*90)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve
)

# PREDIKSI DATA UJI
y_pred = pipeline.predict(X_test)
y_prob = pipeline.predict_proba(X_test)[:, 1]

# CLASSIFICATION REPORT
report = classification_report(
    y_test,
    y_pred,
    target_names=["Low Risk", "High Risk"],
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

print("\nCLASSIFICATION REPORT")

display(report_df)

# CONFUSION MATRIX
cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=["Actual Low Risk", "Actual High Risk"],
    columns=["Predicted Low Risk", "Predicted High Risk"]
)

print("\nCONFUSION MATRIX")

display(cm_df)

# VISUALISASI CONFUSION MATRIX
plt.figure(figsize=(6,5))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Low Risk", "High Risk"]
)

disp.plot(cmap="Blues", values_format="d")

plt.title("Confusion Matrix Random Forest")

plt.show()

# METRIK EVALUASI
accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

roc_auc = roc_auc_score(y_test, y_prob)

metric_df = pd.DataFrame({

    "Metric":[

        "Accuracy",

        "Precision",

        "Recall",

        "F1-Score",

        "ROC AUC"

    ],

    "Score":[

        accuracy,

        precision,

        recall,

        f1,

        roc_auc

    ]

})

print("\nHASIL EVALUASI MODEL")

display(metric_df)

# ROC CURVE
fpr, tpr, threshold = roc_curve(y_test, y_prob)

plt.figure(figsize=(6,5))

plt.plot(
    fpr,
    tpr,
    label=f"ROC AUC = {roc_auc:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve Random Forest")

plt.legend()

plt.grid(True)

plt.show()

# RINGKASAN HASIL EVALUASI
summary_eval = pd.DataFrame({

    "Keterangan":[

        "Jumlah Data Uji",

        "Jumlah Prediksi",

        "Accuracy",

        "Precision",

        "Recall",

        "F1-Score",

        "ROC AUC"

    ],

    "Nilai":[

        len(X_test),

        len(y_pred),

        round(accuracy,4),

        round(precision,4),

        round(recall,4),

        round(f1,4),

        round(roc_auc,4)

    ]

})

print("\nRINGKASAN HASIL EVALUASI")

display(summary_eval)

# PERBANDINGAN MODEL SEBELUM DAN SESUDAH SMOTE
from sklearn.pipeline import Pipeline as SkPipeline

print("\nPERBANDINGAN MODEL SEBELUM DAN SESUDAH SMOTE")

# Model TANPA SMOTE
rf_no_smote = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42
)

rf_no_smote.fit(X_train, y_train)

pred_no = rf_no_smote.predict(X_test)
prob_no = rf_no_smote.predict_proba(X_test)[:,1]

# Model DENGAN SMOTE
pred_smote = pipeline.predict(X_test)
prob_smote = pipeline.predict_proba(X_test)[:,1]

comparison_metric = pd.DataFrame({

    "Metrik":[
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "ROC-AUC"
    ],

    "Sebelum SMOTE":[
        accuracy_score(y_test,pred_no),
        precision_score(y_test,pred_no),
        recall_score(y_test,pred_no),
        f1_score(y_test,pred_no),
        roc_auc_score(y_test,prob_no)
    ],

    "Sesudah SMOTE":[
        accuracy_score(y_test,pred_smote),
        precision_score(y_test,pred_smote),
        recall_score(y_test,pred_smote),
        f1_score(y_test,pred_smote),
        roc_auc_score(y_test,prob_smote)
    ]

})

comparison_metric.iloc[:,1:] = comparison_metric.iloc[:,1:].round(4)

display(comparison_metric)



print("\nEVALUASI MODEL SELESAI")

# 11. ANALISIS FEATURE IMPORTANCE
print("\n" + "="*90)
print("11. ANALISIS FEATURE IMPORTANCE")
print("="*90)

# MENGAMBIL MODEL RANDOM FOREST DARI PIPELINE
rf_model = pipeline.named_steps["rf"]

# MENGAMBIL NILAI FEATURE IMPORTANCE
importance_df = pd.DataFrame({

    "Feature": X_train.columns,

    "Importance": rf_model.feature_importances_

})

# MENGURUTKAN BERDASARKAN NILAI TERBESAR
importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

importance_df.insert(
    0,
    "Ranking",
    range(1, len(importance_df)+1)
)

print("\nHASIL FEATURE IMPORTANCE")

display(importance_df)

# MENAMPILKAN 3 FITUR PALING BERPENGARUH
top3 = importance_df.head(3)

print("\n3 FITUR PALING BERPENGARUH")

display(top3)

# RINGKASAN FEATURE IMPORTANCE
summary_df = pd.DataFrame({

    "Keterangan":[

        "Jumlah Feature",

        "Feature Paling Berpengaruh",

        "Nilai Importance Tertinggi"

    ],

    "Nilai":[

        len(importance_df),

        importance_df.iloc[0]["Feature"],

        round(importance_df.iloc[0]["Importance"],4)

    ]

})

print("\nRINGKASAN FEATURE IMPORTANCE")

display(summary_df)

# VISUALISASI FEATURE IMPORTANCE
plt.figure(figsize=(10,6))

plt.barh(

    importance_df["Feature"],

    importance_df["Importance"]

)

plt.gca().invert_yaxis()

plt.xlabel("Feature Importance")

plt.ylabel("Feature")

plt.title("Feature Importance Random Forest")

plt.grid(axis="x", linestyle="--", alpha=0.5)

plt.show()

print("\nANALISIS FEATURE IMPORTANCE SELESAI")

# 12. SIMPAN MODEL
import joblib
import os

MODEL_DIR = r"C:\honeypot-risk-classifier\backend\model"
os.makedirs(MODEL_DIR, exist_ok=True)

MODEL_PATH = os.path.join(MODEL_DIR, "rf_model.pkl")

joblib.dump(pipeline, MODEL_PATH)

print("=" * 60)
print("MODEL BERHASIL DISIMPAN")
print(MODEL_PATH)
print("=" * 60)